package com.guille.WebSalud20.Enumeracion;

public enum Especialidad {
    CARDIOLOGIA, 
//    CIRUGIA_GENERAL,
//    CIRUGIA_MAXILOFACIAL,
//    CIRUGIA_PEDIATRICA,
    DERMATOLOGIA, 
    NUTRICION, 
    GINECOLOGIA_Y_OBSTETRICIA,
    HEMATOLOGIA,
    INFECTOLOGIA,
    MEDICINA_GENERAL,
    TRAUMATOLOGIA, 
    NEUROLOGIA, 
    OFTALMOLOGIA, 
    ONCOLOGIA, 
    DIABETOLOGIA, 
    PEDIATRIA
}